services:
  mysql:
    image: mysql:latest
    container_name: mysqldb_dwbh
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - springboot-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_dwbh
    restart: always
    environment:
      PMA_HOST: mysqldb_dwbh
      PMA_PORT: 3309
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8090:80"
    networks:
      - springboot-network

  mongo:
    image: mongo
    ports:
      - '27019:27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - springboot-network

volumes:
  db_data:
  mongodb-data:

networks:
  springboot-network:
    driver: bridge
