services:
  mysql:
    image: mysql:latest
    container_name: mysqldb_dwbh
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - springboot-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_dwbh
    restart: always
    environment:
      PMA_HOST: mysqldb_dwbh
      PMA_PORT: 3309
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8090:80"
    networks:
      - springboot-network

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - springboot-network

  redis_container:
    image: redis:latest
    container_name: redis-pub-container
    # 접근 포트 설정(컨테이너 외부:컨테이너 내부)
    hostname: dwbh
    ports:
      - 6380:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server /usr/local/conf/redis.conf

volumes:
  db_data:
  mongodb-data:

networks:
  springboot-network:
    driver: bridge
