spring:
  application:
    name: dwbh
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost:3306/dwbh
    username: dwbh
    password: dwbh
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy # log4j2 driver class name
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: dwbh
      password: dwbh
      database: dwbh
      uri: mongodb://localhost:27017/dwbh

springdoc:
  packages-to-scan: com.dwbh.backend
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /

logging:
  file:
    path: C:/logs/dwbh/backend
  level:
    root: info
    org.springframework.web: info
    com.zaxxer.hikari: info
    log4jdbc.log4j2: error
    jdbc.sqlonly: info
    jdbc.resultsettable: info
    jdbc.connection: info
